export const pricingPlans = [
  {
    name: "Starter",
    variantId: "1842724",
    originalPrice: "$9.99",
    price: "$5.99",
    period: "/mes",
    credits: "40 créditos/mes",
    highlighted: false,
    features: [
      "40 créditos/mes",
      "1 crédito = 1 creativo",
      "3 formatos (1:1, 4:5, 9:16)",
      "4 ángulos de venta",
      "Soporte por email",
    ],
  },
  {
    name: "Pro",
    variantId: "1842974",
    originalPrice: "$24.99",
    price: "$19.99",
    period: "/mes",
    credits: "150 créditos/mes",
    highlighted: true,
    features: [
      "150 créditos/mes",
      "1 crédito = 1 creativo",
      "Todos los formatos y estilos",
      "4 ángulos de venta",
      "Historial de campañas",
      "Soporte prioritario",
    ],
  },
  {
    name: "Business",
    variantId: "1842976",
    originalPrice: "$59.99",
    price: "$49.99",
    period: "/mes",
    credits: "500 créditos/mes",
    highlighted: false,
    features: [
      "500 créditos/mes",
      "1 crédito = 1 creativo",
      "Todo lo del plan Pro",
      "White label",
      "API access",
      "Soporte 24/7",
      "Múltiples usuarios",
    ],
  },
]
